export const sagaActions = {
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  CLEAR_ERROR_REQUEST: "CLEAR_ERROR_REQUEST",
  CLEAR_ERROR_SUCCESS: "CLEAR_ERROR_SUCCESS",
  CLEAR_ERROR_FAILURE: "CLEAR_ERROR_FAILURE",
};
